" 制表符替换为4个空格
set expandtab | set tabstop=4 | set shiftwidth=4

" 对lua，制表符和缩进都是两个空格
au FileType lua,clj,html,js
    \ set expandtab | set tabstop=2 | set shiftwidth=2

" 设置换行符
set fileformats=unix

" 检测文件编码时，优先考虑 UTF-8
set fileencodings=utf-8,ucs-bom,gbk,gb2312,big5,latin1

" 不用交换文件
set noswapfile

" 显示当前行
set cursorline

" 搜索时忽略大小写（ignorecase）。但是，如果搜索模式里有大写字母，就不再忽略大小写（smartcase）。
set ignorecase
set smartcase

" 即时显示匹配结果（incsearch），并高亮所有结果（hlsearch）。
set incsearch
set hlsearch

" 高亮不想要的行尾空格
" See [http://vim.wikia.com/wiki/Highlight_unwanted_spaces]
" - highlight trailing whitespace in red
" - have this highlighting not appear whilst you are typing in insert mode
" - have the highlighting of whitespace apply when you open new buffers
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches() " for performance

" 默认加载括号识别
let g:rainbow_active = 1

" 默认加载缩进线
colorscheme darkblue
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
let g:indent_guides_guide_size = 1
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd guibg=red ctermbg=1
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=1
